# Generated by Django 6.0.6 on 2026-06-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('focus', models.CharField(choices=[('competitive', 'Competitive'), ('casual', 'Casual'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('games', models.ManyToManyField(blank=True, related_name='clans', to='games.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clans.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clan', 'user')},
            },
        ),
        migrations.AddField(
            model_name='clan',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clans', through='clans.ClanMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
