# Generated by Django 6.0.6 on 2026-06-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.URLField(blank=True)),
                ('mode', models.CharField(choices=[('tournament', 'Tournament'), ('scrim', 'Scrim'), ('community', 'Community')], default='tournament', max_length=20)),
                ('format', models.CharField(blank=True, max_length=40)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('prize', models.CharField(blank=True, max_length=80)),
                ('starts_at', models.DateTimeField()),
                ('max_teams', models.PositiveSmallIntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='games.game')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
