# Generated by Django 6.0.6 on 2026-06-11 13:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tag', models.CharField(blank=True, help_text='Discriminator, e.g. 1337', max_length=10)),
                ('avatar', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('region', models.CharField(blank=True, help_text='EU, NA, ...', max_length=40)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('is_online', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('playstyle', models.CharField(choices=[('competitive', 'Competitive'), ('casual', 'Casual')], default='competitive', max_length=20)),
                ('looking_for', models.CharField(choices=[('team', 'Team'), ('clan', 'Clan'), ('players', 'Players'), ('any', 'Any')], default='any', max_length=20)),
                ('main_roles', models.JSONField(blank=True, default=list)),
                ('availability_days', models.JSONField(blank=True, default=list)),
                ('availability_from', models.CharField(blank=True, max_length=10)),
                ('availability_to', models.CharField(blank=True, max_length=10)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('kd', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(blank=True, max_length=80)),
                ('rank', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
