# Generated by Django 6.0.6 on 2026-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='online', max_length=20),
        ),
    ]
