# Generated by Django 6.0.6 on 2026-06-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GameSquad', max_length=80)),
                ('allow_registration', models.BooleanField(default=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('groq_model', models.CharField(blank=True, max_length=120)),
                ('openrouter_model', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
